apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-ddns-credentials
  labels:
    app.kubernetes.io/name: ddns-cloudflare
    app.kubernetes.io/component: infra
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: {{ .Values.secret.name }}
    creationPolicy: Owner
  data:
    - secretKey: api-token
      remoteRef:
        key: {{ .Values.secret.awsSecretKey }}
        property: cloudflare_api-token
