{{- if .Values.gateway.prometheus.enabled }}
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: prometheus-remote-write-vs
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - {{ .Values.gateway.prometheus.host | quote }}
  gateways:
    - {{ .Values.gateway.prometheus.gatewayRef | default "istio-system/goormgb-gateway" }}
  http:
    - name: prometheus-remote-write
      match:
        - method:
            exact: POST
          uri:
            exact: /api/v1/write
      route:
        - destination:
            host: prom-prometheus
            port:
              number: 9090
    - name: prometheus-health
      match:
        - uri:
            exact: /-/ready
        - uri:
            exact: /-/healthy
      route:
        - destination:
            host: prom-prometheus
            port:
              number: 9090
{{- end }}
