{{- if .Values.initialConfig.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudbeaver-initial-config
  labels:
    app: cloudbeaver
data:
  .project: |
    <?xml version="1.0" encoding="UTF-8"?>
    <projectDescription>
      <name>GlobalConfiguration</name>
      <comment>General DBeaver project</comment>
      <projects/>
      <buildSpec/>
      <natures>
        <nature>org.jkiss.dbeaver.DBeaverNature</nature>
      </natures>
    </projectDescription>
  data-sources.json: |
    {{- .Values.initialConfig.dataSources | nindent 4 }}
{{- end }}
