{{- if .Values.virtualService.enabled }}
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: cloudbeaver-dr
spec:
  host: cloudbeaver.monitoring.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE
{{- end }}
