# k3s - DDNS Route53 설정
# Domain: goormgb.space

domain: "goormgb.space"
hostedZoneID: "Z0444756O5UQIM83AJHO"

records:
  - ""              # goormgb.space (root)
  - "api"           # api.goormgb.space
  - "dev"           # dev.goormgb.space
  - "api.dev"       # api.dev.goormgb.space
  - "argocd"        # argocd.goormgb.space
  - "grafana"       # grafana.goormgb.space
  - "kiali"         # kiali.goormgb.space
