# queue - Staging 환경
fullnameOverride: "queue"
replicaCount: 1

image:
  # TODO: staging CI/CD 구축 후 staging/playball/web/queue 로 전환
  name: "dev/goormgb/queue"
  tag: "e850e82"
  pullPolicy: Always

imagePullSecrets:
  - name: ecr-pull-secret

tolerations:
  - key: "spot"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

istio:
  sidecar: true

servicePort: &port 8081
service:
  type: ClusterIP
  port: *port

envFrom:
  - configMapRef:
      name: service-config
  - secretRef:
      name: service-config

livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: *port
  initialDelaySeconds: 60
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: *port
  initialDelaySeconds: 30
  periodSeconds: 5

otel:
  enabled: false
