# Mail Config - Staging 환경
enabled: true

secretName: mail-config
namespace: staging-webs

secretManager:
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  key: staging/services/mail
  refreshInterval: 1h
