{{- if .Values.serviceConfig.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: service-config
  namespace: {{ .Values.serviceConfig.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.clusterSecretStore.name }}
    kind: ClusterSecretStore
  target:
    name: service-config
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.serviceConfig.secretManagerKey }}
{{- end }}
