# kubeadm-dev - cert-manager ClusterIssuer 설정
# Domain: goormgb.homes

# CP 노드에 배치 (설정 관련)
nodeSelector:
  kubernetes.io/hostname: mini-gmk

tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"

email: "212clab@gmail.com"

route53:
  region: ap-northeast-2
  hostedZoneID: "Z04073612LBMT2Z1I30S4"

certificates:
  - name: goormgb-tls
    dnsNames:
      - "*.goormgb.homes"
      - "*.dev.goormgb.homes"
      - "goormgb.homes"
    issuerRef: letsencrypt-prod # 새 도메인이라 prod 사용 가능
