{{- if .Values.alertmanager.discord.eso.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-discord-webhook
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: alertmanager-discord-webhook
  data:
    - secretKey: webhook-url
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: {{ .Values.alertmanager.discord.eso.secretManagerKey }}
        metadataPolicy: None
        property: webhookUrl
{{- end }}
