{{- if .Values.gateway.grafana.enabled }}
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: grafana-gateway
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: {{ .Values.gateway.grafana.tls.credentialName | default "goormgb-tls" }}
      hosts:
        - {{ .Values.gateway.grafana.host | quote }}
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - {{ .Values.gateway.grafana.host | quote }}
      tls:
        httpsRedirect: true
{{- end }}
