# Mail Config - Prod 환경
enabled: true

secretName: mail-config
namespace: prod-webs

secretManager:
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  key: prod/services/mail
  refreshInterval: 1h
