# PostgreSQL
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  project: default
  source:
    repoURL: git@github.com:goorm-gongbang/303-goormgb-k8s-helm.git
    targetRevision: argocd-sync/dev
    path: dev/charts/data/postgresql
    helm:
      valueFiles:
        - ../../../values/values-data.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: data
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 10s
        maxDuration: 3m
        factor: 2
    syncOptions:
      - CreateNamespace=true
---
# Redis Cache - 세션/캐시용
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-cache
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  project: default
  source:
    repoURL: git@github.com:goorm-gongbang/303-goormgb-k8s-helm.git
    targetRevision: argocd-sync/dev
    path: dev/charts/data/redis
    helm:
      releaseName: redis-cache
      valueFiles:
        - ../../../values/values-redis-cache.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: data
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 10s
        maxDuration: 3m
        factor: 2
    syncOptions:
      - CreateNamespace=true
---
# MongoDB - AI Agent 로깅용 (아직 미배포)
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: mongodb
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: git@github.com:goorm-gongbang/303-goormgb-k8s-helm.git
#     targetRevision: argocd-sync/dev
#     path: dev/charts/data/mongodb
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: data
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true
---
# Redis Queue - 대기열 전용
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-queue
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  project: default
  source:
    repoURL: git@github.com:goorm-gongbang/303-goormgb-k8s-helm.git
    targetRevision: argocd-sync/dev
    path: dev/charts/data/redis
    helm:
      releaseName: redis-queue
      valueFiles:
        - ../../../values/values-redis-queue.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: data
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 10s
        maxDuration: 3m
        factor: 2
    syncOptions:
      - CreateNamespace=true
