{{- if .Values.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.secretName }}
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: {{ .Values.secretManager.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.secretManager.secretStoreRef.name }}
    kind: {{ .Values.secretManager.secretStoreRef.kind }}
  target:
    name: {{ .Values.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: MAIL_HOST
      remoteRef:
        key: {{ .Values.secretManager.key }}
        property: MAIL_HOST
    - secretKey: MAIL_PORT
      remoteRef:
        key: {{ .Values.secretManager.key }}
        property: MAIL_PORT
    - secretKey: MAIL_USERNAME
      remoteRef:
        key: {{ .Values.secretManager.key }}
        property: MAIL_USERNAME
    - secretKey: MAIL_PASSWORD
      remoteRef:
        key: {{ .Values.secretManager.key }}
        property: MAIL_PASSWORD
{{- end }}
