{{- if .Values.oidc.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kiali-oidc-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: kiali-oidc-secret
  data:
    - secretKey: oidc-secret
      remoteRef:
        key: {{ .Values.oidc.secretManagerKey }}
        property: clientSecret
{{- end }}
