apiVersion: v2
name: kiali
description: Kiali - Istio Service Mesh Observability
type: application
version: 1.0.0
appVersion: "2.23.0"

dependencies:
  - name: kiali-server
    version: "2.23.0"
    repository: oci://__AWS_ACCOUNT_ID__.dkr.ecr.ap-northeast-2.amazonaws.com/helm
