apiVersion: v1
kind: Service
metadata:
  name: alertmanager-discord-relay
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app.kubernetes.io/name: alertmanager-discord-relay
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
  type: ClusterIP
