# Calico CNI with Tigera Operator
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calico
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"  # CNI는 가장 먼저 설치
spec:
  project: default
  source:
    repoURL: git@github.com:goorm-gongbang/303-goormgb-k8s-helm.git
    targetRevision: argocd-sync/dev
    path: common-charts/infra/calico
    helm:
      valueFiles:
        - ../../../dev/values/core/values-calico.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: tigera-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /status
        - /spec/conversion
        - /metadata/annotations
    - group: operator.tigera.io
      kind: Installation
      jsonPointers:
        - /status
    - group: operator.tigera.io
      kind: APIServer
      jsonPointers:
        - /status
