# EKS Prod 클러스터 Istio 설정

apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default

  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          serviceAnnotations:
            service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
            service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"

  meshConfig:
    accessLogFile: /dev/stdout
