apiVersion: v2
name: external-secrets
description: External Secrets Operator wrapper chart
type: application
version: 0.1.0
appVersion: "2.1.0"

dependencies:
  - name: external-secrets
    version: "2.1.0"
    repository: oci://__AWS_ACCOUNT_ID__.dkr.ecr.ap-northeast-2.amazonaws.com/helm
