apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: policy-reporter-ui-disable-mtls
  namespace: kyverno
spec:
  host: policy-reporter-ui-proxy.kyverno.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE
