{{- if .Values.telemetry.tracing.enabled }}
apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: mesh-default
  namespace: istio-system
spec:
  tracing:
    - providers:
        - name: zipkin
      randomSamplingPercentage: {{ .Values.telemetry.tracing.sampling | default 100 }}
      customTags:
        istio.cluster_id:
          literal:
            value: "Kubernetes"
{{- end }}
