{{- if .Values.thanosObjstore.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.thanosObjstore.secretName }}
  namespace: monitoring
type: Opaque
stringData:
  objstore.yml: |
    type: S3
    config:
      bucket: {{ .Values.thanosObjstore.bucket }}
      endpoint: {{ default (printf "s3.%s.amazonaws.com" .Values.thanosObjstore.region) .Values.thanosObjstore.endpoint }}
      region: {{ .Values.thanosObjstore.region }}
{{- end }}
