{{- if .Values.policies.requireLabels.enabled }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-labels
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    policies.kyverno.io/title: Require Labels
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/description: >-
      Pod에 필수 라벨이 있는지 확인합니다.
spec:
  validationFailureAction: {{ .Values.validationAction | default "Audit" }}
  background: true
  rules:
    - name: check-labels
      match:
        any:
          - resources:
              kinds:
                - Pod
              operations:
                - CREATE
      exclude:
        any:
          - resources:
              namespaces:
                {{- range .Values.excludeNamespaces }}
                - {{ . }}
                {{- end }}
      validate:
        message: "Pod에는 운영에 필요한 필수 라벨들이 포함되어야 합니다."
        pattern:
          metadata:
            labels:
              {{- range .Values.policies.requireLabels.requiredLabels }}
              {{ . }}: "?*"
              {{- end }}
{{- end }}
