{{- $ecr := .Values.ecr -}}
{{- range .Values.applications }}
{{- if .enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  {{- if hasPrefix "../" .valuesFile }}
  {{/* 외부 values 파일 사용 시 multi-source */}}
  sources:
    - repoURL: {{ .repoURL }}
      targetRevision: {{ .targetRevision | default "HEAD" }}
      ref: values
    - repoURL: {{ .repoURL }}
      targetRevision: {{ .targetRevision | default "HEAD" }}
      path: {{ .path }}
      helm:
        valueFiles:
          - $values/{{ .valuesFile | replace "../../../" "" }}
        {{- if $ecr.accountId }}
        valuesObject:
          ecr:
            accountId: "{{ $ecr.accountId }}"
            region: "{{ $ecr.region }}"
        {{- end }}
  {{- else }}
  {{/* chart 내부 values 파일 사용 시 single-source */}}
  source:
    repoURL: {{ .repoURL }}
    targetRevision: {{ .targetRevision | default "HEAD" }}
    path: {{ .path }}
    helm:
      valueFiles:
        - {{ .valuesFile }}
  {{- end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .namespace }}
  {{- if .ignoreDifferences }}
  ignoreDifferences:
    {{- toYaml .ignoreDifferences | nindent 4 }}
  {{- end }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
{{- end }}
