{{- if .Values.oidc.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  url: https://{{ .Values.gateway.host }}
  # Local admin 비활성화 (Google OAuth만 허용)
  admin.enabled: "false"
  oidc.config: |
    name: {{ .Values.oidc.name }}
    issuer: {{ .Values.oidc.issuer }}
    clientID: $argocd-google-oauth:clientId
    clientSecret: $argocd-google-oauth:clientSecret
    redirectURI: https://{{ .Values.gateway.host }}/auth/callback
    requestedScopes:
      {{- range .Values.oidc.requestedScopes }}
      - {{ . }}
      {{- end }}
{{- end }}
