{{- if and .Values.notifications.enabled .Values.notifications.discord.eso.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: argocd-notifications-secret
  data:
    - secretKey: discord-webhook-url
      remoteRef:
        key: {{ .Values.notifications.discord.eso.secretManagerKey }}
        property: webhookUrl
{{- end }}
