apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: argocd-vs
spec:
  hosts:
    - {{ .Values.gateway.host | quote }}
  gateways:
    - istio-system/goormgb-gateway
  http:
    - route:
        - destination:
            host: argocd-server.argocd.svc.cluster.local
            port:
              number: 80
