# OAuth2 Proxy - Swagger 인증
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oauth2-proxy
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"  # Istio 이후, App 이전
spec:
  project: default
  source:
    repoURL: git@github.com:goorm-gongbang/303-goormgb-k8s-helm.git
    targetRevision: argocd-sync/dev
    path: dev/charts/security/oauth2-proxy
    helm:
      valueFiles:
        - ../../../values/security/values-oauth2-proxy.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
