# 서비스 공용 시크릿 (ESO)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-6"  # 앱 시크릿
spec:
  project: default
  source:
    repoURL: git@github.com:goorm-gongbang/303-goormgb-k8s-helm.git
    targetRevision: argocd-sync/dev
    path: dev/charts/security/service-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: dev-webs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
