---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-ddns-credentials
  namespace: istio-system
spec:
  encryptedData:
    api-token: AgBn0gMuEtqWgqtfhhrI8gb4hYoBk8bNmoQu7ALGrM2W0d9J6DDnajCFsCxGUjfz02otru2IYJIpb+xirOqe8lp6lQ+DB+q/+7tRPbVKdZ0B3QFhVrOZIRnSQojPG5CJkXo0gavLUSVTRRBu5lFVcA2/enqr+F5XEsTwQ2sf1nBNyK/C5+nrwxGCMfFtoN0IsmzpFdVdoCHE/fUM7F5aTDeS9g1+fXH+GBM3/vFlLcJcEyQUdoQMAdCzC2l393J+p1iRXC6EKt8SC55D0Nttak8+b6ZeCn6ukxDJUAYtAYtcEDc0OmLmgYcv/r1wI6a2JHUMNWF9ex1NKcG47Yu5vW4/5AvGeb4TlmaQGDhfs6p+W+oNc/nqhMpulNEns3B/aVmqboTpgevfuL8v52MttuGAY4tF6I1f5EU6byZCGisv82sl8emKTe7zL7v2+z/tMGv6Kkyg1sEgAslSL0ce6oRHEjLGgRZR71eQN7+udfK5tl86kc3CrNo9wo86gzw1Yag6fk6CK4Zvj/0ZJpsI3za9ko5/RCQAema35qU2g5IrPf4bJWAVO6GMfM6mbhuPoqN13X/KecLM0UIFrkaE9GbpVxE2Lg/eUd+PD78p+aBJBeBnSa1x7N2iBa9xyZR5Eqb0pVNNBOl4296Qz/3WPsW9Lbg2w4O6vqsXGXqHWtV/8y9OStuOnyBn+toJ9sO1iY+nJNRf2/jn7vDIehw6kfSmkz7bJcQdQDo21xOtDqp/yg7lzmo2/Il8lwrVfqkJhFhK//VzRQ==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-ddns-credentials
      namespace: istio-system
    type: Opaque
