---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgresql-credentials
  namespace: data
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgA2JLHpDEYUvZyhxn2Rqd04U1b3Zz+CvA0libBbG7bfDLN3kMm7jAwHchkfveuObeJWMZGW5E5SyH8o5uS9dzVG5AVH8f9bzKO4Vx5JNijtFCL/uIsjNwDX2CsVSYo70BfWTbPWs2J/DmNgJLtpt4BedV7HqbcMqF1f3E+0iYE7vkiVcdW+CqBeBj8pdNm1fUCy+xLaDPP4yvK3EWWKv00bgXPW2aMLMgixd549v9f8GHqpZeiKbj4LgX8WPWrcns2PWXCYa9Y/kdIcVk3Ky/pmgHiLTicOXS8XDnvHBwMIcunNY4tjFCaOxKuRPdfvwg1Nhj3V34UpOXsIe4vGhFqBwvtvRhSH9LxOM7O8/PtG9mG79rYmAJYott1bQokCKML1g8M2cnVd59/Y+0G1NblPirVIScOPoz9ylWRid4vicflnIvmck80zdgiBnYlPX6LRnBVAAg8sBEcPrNsPTZ5dWirlphhBrHx/utP3bGX779iWghM2iPqtAeP69WQbfdKxulVI9byuXska3HuJTSqSUiT2NSj2X66cVF+4zx0MosdG6qAut/nvtqsCvYZhUf888TKWLVFj3yUajTObby12+8xyJ9nXh/dRZtHW5/UcGVHNpNSaFO+9fh6b0EAUtZM49p69WYZo/nTTwjl6IxFJS+yJY10xkf5mHF88XbsVfkLeGlPCfO+JkGO0j0QJiq4OBKeHDJG/wsBJ8KQI6H9eO4dylg==
    POSTGRES_USER: AgAvuF0QMOyEr6O9jYKT5eAoiktvIEmOSgWOiD/tijcYIO5/UXzmMiV6ghRm6mLD0RnwN2nkcu/SgMAcoXwLoPa0dYwY/dSRmPKbPlqn2yfjPGrEFuP7UXmYgKWjc5HjkL3to/CmKXwJWGAicD5QRF1lB8bjeGVlXVNJ/dDgOz6LYwEunpL3zi9aJBc66guJppIqkAMJQfYRDvNonjDxPn+d4ByydwZciHVCFsLrqi1iPrbAX02vcGdbh6yFSaFn7JnbyYLyHXM13P+tmU7AdatBUtSWnJr0XpoHAbELzS3ZxWvpCukeM8Asq5a0jOOtbqwZ1/3Y+S01dyiEpBRExv7l2AyIHP3nddvk1YWUqLm+/omj9Jkp8t8lghldq7xiFt6e/zXawrVw2STBbdwDX3EzPf820K0TSvOcneMAtZRhH1PzN+bkmwuUMNXF2A3+CyTFNk92eQeBeNIcMnOxcVtfMmb0xnwxsujVyrrAfdM8U2WpZRd8t6qSsRjDm6keiST9gW5u7Zrz1V0CeqOVTzRrYV9ChKJ6fyFx686wRMyvOgMJvzI7doefZT+jEhSHq0jhJUw7EN9vgbE0ta4EtYPxOJU36kLtt6E/pc5ZfcAua8eCRIHMKTyUMOBTikKpDEu1J8wZaD+Zo0/0D5IrDrOAbpXfuFO47w6kg592Q8W37RMvCMXbBka7QMNaeLA3WeFO5UENUYgZUA==
  template:
    metadata:
      annotations:
        argocd.argoproj.io/tracking-id: postgresql:external-secrets.io/ExternalSecret:data/postgresql-credentials
        reconcile.external-secrets.io/data-hash: 30f2901fe92cb03b3e2354e20935f90aebfd20c621cc91ce062b2208
      creationTimestamp: null
      labels:
        reconcile.external-secrets.io/created-by: c2c54993b307a3f8eeea38673eccaa416172420b2c086073b1c5386c
        reconcile.external-secrets.io/managed: "true"
      name: postgresql-credentials
      namespace: data
    type: Opaque
