apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # 순서 중요: namespaces 먼저 (sync-wave: -10)
  - infra/namespaces.yaml
  - infra/ecr-creds.yaml
  - infra/eso.yaml
  - infra/cert-manager.yaml
  - infra/ddns.yaml
  - infra/data.yaml
  - infra/rbac.yaml
  - infra/argocd.yaml
  - infra/istio.yaml
  - infra/monitoring.yaml
  - dev.yaml
