{{- if .Values.eso.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: oauth2-proxy-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        OAUTH2_PROXY_CLIENT_ID: "{{ "{{ .clientId }}" }}"
        OAUTH2_PROXY_CLIENT_SECRET: "{{ "{{ .clientSecret }}" }}"
        OAUTH2_PROXY_COOKIE_SECRET: "{{ "{{ .cookieSecret }}" }}"
  data:
    - secretKey: clientId
      remoteRef:
        key: {{ .Values.eso.secretKey }}
        property: client_id
    - secretKey: clientSecret
      remoteRef:
        key: {{ .Values.eso.secretKey }}
        property: client_secret
    - secretKey: cookieSecret
      remoteRef:
        key: {{ .Values.eso.secretKey }}
        property: cookie_secret
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-emails
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: oauth2-proxy-emails
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        authenticated-emails.txt: "{{ "{{ .emails }}" }}"
  data:
    - secretKey: emails
      remoteRef:
        key: {{ .Values.eso.secretKey }}
        property: authenticated_emails
{{- end }}
