{{- if .Values.clusterSecretStore.enabled }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.clusterSecretStore.name }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.clusterSecretStore.region }}
      # IRSA 사용 - ServiceAccount를 통해 IAM Role 인증
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.clusterSecretStore.serviceAccount.name }}
            namespace: {{ .Values.clusterSecretStore.serviceAccount.namespace }}
{{- end }}
