# EKS Prod - Namespace 설정
# Istio sidecar injection 활성화

namespaces:
  - name: prod-webs
    istio: true
  - name: data
    istio: false
  - name: monitoring
    istio: false  # 모니터링은 sidecar 불필요
  - name: external-dns
    istio: false  # ExternalDNS는 sidecar 불필요
  - name: prod-ai
    istio: true
  - name: data
    istio: false
  - name: messaging
    istio: false
