{{- if and .Values.oauth2Proxy.enabled .Values.oauth2Proxy.eso.enabled }}
# OAuth2 Proxy credentials
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "redisinsight.fullname" . }}-oauth
  labels:
    {{- include "redisinsight.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.oauth2Proxy.eso.secretStoreRef.name }}
    kind: {{ .Values.oauth2Proxy.eso.secretStoreRef.kind }}
  target:
    name: {{ include "redisinsight.fullname" . }}-oauth
    creationPolicy: Owner
  data:
    - secretKey: OAUTH2_PROXY_CLIENT_ID
      remoteRef:
        key: {{ .Values.oauth2Proxy.eso.remoteRef.key }}
        property: {{ .Values.oauth2Proxy.eso.remoteRef.propertyPrefix | default "" }}clientId
    - secretKey: OAUTH2_PROXY_CLIENT_SECRET
      remoteRef:
        key: {{ .Values.oauth2Proxy.eso.remoteRef.key }}
        property: {{ .Values.oauth2Proxy.eso.remoteRef.propertyPrefix | default "" }}clientSecret
    - secretKey: OAUTH2_PROXY_COOKIE_SECRET
      remoteRef:
        key: {{ .Values.oauth2Proxy.eso.remoteRef.key }}
        property: {{ .Values.oauth2Proxy.eso.remoteRef.propertyPrefix | default "" }}cookieSecret
---
# Allowed emails list
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "redisinsight.fullname" . }}-emails
  labels:
    {{- include "redisinsight.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.oauth2Proxy.eso.secretStoreRef.name }}
    kind: {{ .Values.oauth2Proxy.eso.secretStoreRef.kind }}
  target:
    name: {{ include "redisinsight.fullname" . }}-emails
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        authenticated-emails.txt: "{{ `{{ .emails }}` }}"
  data:
    - secretKey: emails
      remoteRef:
        key: {{ .Values.oauth2Proxy.eso.remoteRef.key }}
        property: {{ .Values.oauth2Proxy.eso.remoteRef.propertyPrefix | default "" }}allowedEmails
{{- end }}
