{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "infra-console.fullname" . }}-github
  labels:
    {{- include "infra-console.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ include "infra-console.fullname" . }}-github
    creationPolicy: Owner
  data:
    - secretKey: GITHUB_TOKEN
      remoteRef:
        key: {{ .Values.externalSecret.remoteRef.key }}
        property: {{ .Values.externalSecret.remoteRef.property }}
{{- end }}
