# Kiali Server values (OCI chart)
# https://github.com/kiali/helm-charts

auth:
  strategy: anonymous

server:
  web_root: /kiali

external_services:
  prometheus:
    url: http://prom-prometheus.monitoring.svc.cluster.local:9090
  grafana:
    enabled: true
    in_cluster_url: http://grafana.monitoring.svc.cluster.local:80
    url: https://grafana.goormgb.space
  tracing:
    enabled: true
    in_cluster_url: http://tempo.monitoring.svc.cluster.local:3200

# kiali-config (Git chart) values
kialiVirtualService:
  enabled: true
  host: kiali.goormgb.space
