apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    istio: ingressgateway
  servers:
    {{- if .Values.gateway.tls.enabled }}
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: {{ .Values.gateway.tls.credentialName }}
      hosts:
        - {{ .Values.gateway.host | quote }}
    {{- end }}
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - {{ .Values.gateway.host | quote }}
      {{- if .Values.gateway.tls.enabled }}
      tls:
        httpsRedirect: true
      {{- end }}
