# OTel Collector (트레이스/메트릭/로그 수집 및 샘플링)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-collector
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: git@github.com:goorm-gongbang/303-goormgb-k8s-helm.git
    targetRevision: argocd-sync/dev
    path: common-charts/infra/monitoring/otel-collector
    helm:
      valueFiles:
        - ../../../../dev/values/monitoring/values-otel-collector.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
