# Prometheus + Grafana + AlertManager
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    notifications.argoproj.io/subscribe.on-infra-deploy-failed.discord-infra: ""
    notifications.argoproj.io/subscribe.on-infra-health-degraded.discord-infra: ""
spec:
  project: default
  source:
    repoURL: git@github.com:goorm-gongbang/303-goormgb-k8s-helm.git
    targetRevision: argocd-sync/dev
    path: common-charts/infra/monitoring/prometheus-stack
    helm:
      valueFiles:
        - ../../../../dev/values/monitoring/values-monitoring.yaml
        - ../../../../dev/values/monitoring/values-alerting.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: ""
      kind: PersistentVolumeClaim
      jsonPointers:
        - /spec/volumeName
        - /spec/storageClassName
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /status
        - /spec/conversion
        - /metadata/annotations
