# Istio Security (WAF-like protection)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-security
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  project: default
  source:
    repoURL: git@github.com:goorm-gongbang/303-goormgb-k8s-helm.git
    targetRevision: argocd-sync/staging
    path: common-charts/infra/istio-security
    helm:
      valueFiles:
        - ../../../staging/values/values-istio-security.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
