# RBAC Configuration
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rbac
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-7"
spec:
  project: default
  source:
    repoURL: git@github.com:goorm-gongbang/303-goormgb-k8s-helm.git
    targetRevision: argocd-sync/staging
    path: common-charts/infra/rbac
    helm:
      valueFiles:
        - ../../../staging/values/values-rbac.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
