{{- if .Values.cloudflare.secret.awsSecretKey }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-cert-manager-credentials
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/component: cloudflare-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: {{ .Values.cloudflare.secret.name }}
    creationPolicy: Owner
  data:
    - secretKey: api-token
      remoteRef:
        key: {{ .Values.cloudflare.secret.awsSecretKey }}
        property: api-token
{{- end }}
