# Namespaces with Istio injection
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"  # 가장 먼저 생성
spec:
  project: default
  source:
    repoURL: https://github.com/goorm-gongbang/303-goormgb-k8s-helm.git
    targetRevision: argocd-sync/eks
    path: common-charts/infra/namespaces
    helm:
      valueFiles:
        - ../../../eks/values/common/values-namespaces.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
