{{- if .Values.backup.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: logs-backup-s3
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: logs-backup-s3
    creationPolicy: Owner
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: {{ .Values.backup.externalSecret.remoteRef }}
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: {{ .Values.backup.externalSecret.remoteRef }}
        property: AWS_SECRET_ACCESS_KEY
{{- end }}
