apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  labels:
    app: clickhouse
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
    - name: native
      port: {{ .Values.service.nativePort }}
      targetPort: native
      protocol: TCP
    - name: metrics
      port: 9363
      targetPort: metrics
      protocol: TCP
  selector:
    app: clickhouse
