{{- if .Values.hubbleUI.enabled }}
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: hubble-ui
  namespace: kube-system
spec:
  hosts:
    - {{ .Values.hubbleUI.host | quote }}
  gateways:
    - istio-system/goormgb-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: hubble-ui.kube-system.svc.cluster.local
            port:
              number: 80
{{- end }}
